title: Oscar Learning to Pages in Github
author: Oscar M. Díaz B.
email: oscarmdiazb@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A first time blog to explore wether hosting my personal and professional
  in Github makes sense

# social links
twitter_username: oscarmadiazb # DO NOT include the @ character, or else the build will fail!
github_username:  oscarmadiazb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
